name: Build and Test CGo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile C Files
      run: |
        gcc -c -o hello.o hello.c

    - name: Create C Library
      run: |
       ar rcs libhello.a hello.o

    - name: Run the application
      run: |
        go run main.go

    # - name: Build Docker image
    #   run: |
    #     docker build -t cgo-hello-world .

    # - name: Test Docker image
    #   run: |
    #     docker run --rm cgo-hello-world
